### ISSUE TITLE
Installation issu: RTAlib/SetupDB/setup_db.sh Does not exist anymore.

### ISSUE THREAD

**Issue by jacquemier** [rta-pipe/RTAlib#71]
Following installation procedure in README.md file give the following error:

_promt%> bash RTAlib/SetupDB/setup_db.sh  
bash: RTAlib/SetupDB/setup_db.sh: No such file or directory_

Any Idea ?

Thanks, Jean

**Comment by Leofaber** [comment]
Yes. I removed the script but I did not update the README. Now it is fixed. Thank you.

**Comment by jacquemier** [comment]
Ok,

Could you please also update installation procedure ?
